version = 1

test_patterns = ["*_test.go"]

[[analyzers]]
name = "go"

  [analyzers.meta]
  import_root = "github.com/pablodz/scigo"

[[transformers]]
name = "gofmt"

[[transformers]]
name = "gofumpt"